# Pipeline Configuration with Optimized Timeouts
pipeline:
  name: "ACIS EOD Trading Pipeline"
  version: "2.0.0"
  environment: "production"

execution:
  max_concurrent_scripts: 4
  memory_threshold_gb: 4.0  # Lowered for testing
  disk_threshold_gb: 1.0
  default_timeout: 600  # 10 minutes default
  retry_policy:
    max_attempts: 2  # Reduced for faster testing
    delay_seconds: 10
    backoff_multiplier: 1.5

circuit_breaker:
  failure_threshold: 3  # More lenient
  recovery_timeout: 30
  half_open_requests: 1

scripts:
  ingest:
    - name: "setup_schema.py"
      timeout: 300  # Increased to 5 minutes
      critical: true
      dependencies: []
      resource_profile: "low"
      max_retries: 2
      
    - name: "fetch_symbol_metadata.py"
      timeout: 900  # 15 minutes
      critical: true
      dependencies: ["setup_schema.py"]
      resource_profile: "medium"
      cache_key: "symbols"
      
    - name: "populate_stock_metadata.py"
      timeout: 300  # 5 minutes
      critical: false
      dependencies: ["fetch_symbol_metadata.py"]
      resource_profile: "low"
      
    - name: "fetch_sp500_history.py"
      timeout: 300  # 5 minutes
      critical: false
      dependencies: ["setup_schema.py"]
      cache_key: "sp500"
      
    - name: "fetch_prices.py"
      timeout: 2400  # 40 minutes
      critical: true
      dependencies: ["fetch_symbol_metadata.py"]
      resource_profile: "high"
      incremental: true
      priority: "critical"
      
    - name: "fetch_dividend_history.py"
      timeout: 600  # 10 minutes
      critical: false
      dependencies: ["fetch_prices.py"]
      incremental: true
      
    - name: "fetch_fundamentals.py"
      timeout: 3600  # 60 minutes
      critical: true
      dependencies: ["fetch_prices.py"]
      resource_profile: "high"
      incremental: true

  analysis:
    - name: "compute_forward_returns.py"
      timeout: 600  # 10 minutes
      critical: true
      dependencies: ["fetch_prices.py"]
      resource_profile: "high"
      
    - name: "compute_dividend_growth_scores.py"
      timeout: 600
      critical: false
      dependencies: ["fetch_dividend_history.py"]
      
    - name: "compute_value_momentum_and_growth_scores.py"
      timeout: 900  # 15 minutes
      critical: true
      dependencies: ["fetch_fundamentals.py"]
      resource_profile: "high"
      
    - name: "compute_ai_dividend_scores.py"
      timeout: 600
      critical: false
      dependencies: ["compute_dividend_growth_scores.py"]
      
    - name: "compute_sp500_outperformance_scores.py"
      timeout: 600
      critical: true
      dependencies: ["compute_forward_returns.py"]
      
    - name: "train_ai_value_model.py"
      timeout: 1200  # 20 minutes
      critical: true
      dependencies: ["compute_value_momentum_and_growth_scores.py"]
      resource_profile: "gpu"
      
    - name: "score_ai_value_model.py"
      timeout: 600
      critical: true
      dependencies: ["train_ai_value_model.py"]
      
    - name: "train_ai_growth_model.py"
      timeout: 1200  # 20 minutes
      critical: true
      dependencies: ["compute_value_momentum_and_growth_scores.py"]
      resource_profile: "gpu"
      
    - name: "score_ai_growth_model.py"
      timeout: 600
      critical: true
      dependencies: ["train_ai_growth_model.py"]
      
    - name: "run_rank_value_stocks.py"
      timeout: 300
      critical: true
      dependencies: ["score_ai_value_model.py"]
      
    - name: "run_rank_growth_stocks.py"
      timeout: 300
      critical: true
      dependencies: ["score_ai_growth_model.py"]
      
    - name: "run_rank_dividend_stocks.py"
      timeout: 300
      critical: false
      dependencies: ["compute_ai_dividend_scores.py"]
      
    - name: "run_rank_momentum_stocks.py"
      timeout: 300
      critical: true
      dependencies: ["compute_sp500_outperformance_scores.py"]

materialized_views:
  - name: "mv_latest_annual_fundamentals"
    refresh_concurrently: true
    timeout: 300
    
  - name: "mv_symbol_with_metadata"
    refresh_concurrently: true
    timeout: 180
    
  - name: "mv_latest_forward_returns"
    refresh_concurrently: false
    timeout: 300
    
  - name: "mv_current_ai_portfolios"
    refresh_concurrently: true
    timeout: 180
